include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - lib/l10n/*
    - assets/**/*.gen.dart
    - packages/**/*.gen.dart
linter:
  rules:
    public_member_api_docs: false
