name: github_search
description: A simple application to search the github repository.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: 3.16.0

dependencies:
  api_client:
    path: ./packages/api_client
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  github_repository:
    path: ./packages/github_repository
  hydrated_bloc: ^9.1.3
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.0.11
  rxdart: ^0.27.7
  share_plus: ^6.3.4

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  share_plus_platform_interface: ^3.2.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
